books/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views




urlpatterns = [
    url(r'^viewer.html$', TemplateView.as_view(template_name="viewer.html", content_type="text/html"), name="viewer"),
   
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elibrary/urls.py
from django.contrib import admin
from django.urls import include ,path, re_path 
# from django.conf.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home ,name='Home'),
    path('About/', views.About ,name='About'),
    path('Contact/', views.Contact,name='Contact'),

    #account url
    path('account/login', views.Login,name='handleLogin'),
    path('account/Register', views.Register,name='Register'),
    path('account/Registers', views.handleRegister,name='Registers'),

    #profile
    path('account/profile', views.profile,name='profile'),
    path('account/profile/update', views.Profile_Update,name='Profile_Update'),

    # book app
    path('books/',views.Books ,name='books'),
    path('book_detail/<str:id>', views.Book_Detail ,name="book_detail"),
    path('filter-data/',views.filter_data , name="filter_data"),
    path('search/',views.Search, name="search"),
    # path('viewer/',views.Viewer,name=""),
  
    re_path(r'^viewer.html$', TemplateView.as_view(template_name="viewer.html", content_type="text/html"), name="viewer"),

   
   path('accounts/',include('django.contrib.auth.urls')),
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += (
#     url(r'^viewer.html$', TemplateView.as_view(template_name="viewer.html", content_type="text/html"), name="viewer"),
# )
    
 

books/models.py
from django.db import models
from app.models import Author
from app.models import Publisher
from categories.models import category
# Create your models here.
class Add_book(models.Model):
    name=models.CharField(max_length=350)
    author=models.ForeignKey(Author,on_delete=models.CASCADE)
    publisher=models.ForeignKey(Publisher,on_delete=models.CASCADE)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    publish_year = models.CharField(max_length=100)
    description = models.TextField(blank=True, null= True)
    image=models.ImageField(upload_to='media/book_imgs')
    pdf = models.FileField(upload_to='media/bookapp/pdfs/')
    download = models.CharField(max_length=2, choices=(('1','Active'), ('2','Inactive')), default = 1)
    status = models.CharField(max_length=2, choices=(('1','Active'), ('2','Inactive')), default = 1)


    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.pdf.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)
    

books/views.py
# from django.http import HttpResponse
# from django.shortcuts import redirect,render
# from django.contrib.auth.decorators import login_required
# from books.models import Add_book
# from categories.models import category
# # Create your views here.

books/templates/book_detail.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% block script %}
{% comment %} <script
src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
crossorigin="anonymous"
></script> {% endcomment %}
 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
{% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> {% endcomment %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'flipbook/css/jquery.fancybox.min.css' %}" />
<script type="text/javascript" src="{% static 'flipbook/js/jquery.fancybox.min.js' %}"></script>
<script>
    // Adjust iframe height according to the contents
    parent.jQuery.fancybox.getInstance().update();

    // Close current fancyBox instance
    parent.jQuery.fancybox.getInstance().close();
</script>



{% endblock %} 


<style>
    .fancybox-slide--iframe .fancybox-content {
        width: 95%;
        height: 95%;
        max-width: 100%;
        max-height: 100%;
        margin: 0;
    }
</style>
<main>
    
    <div class="services-area2">
    <div class="container">
    <div class="row">
    <div class="col-xl-12">
    <div class="row">
    <div class="col-xl-12">
    <div class="single-services d-flex align-items-center mb-0">
        
    <div class="features-img">
    <img src="/{{book_detail.image}}" style=" height: 427px;" alt="">
    </div>
    <div class="features-caption">
    <h3>{{book_detail.name}}</h3>
    <p>By {{book_detail.author}}</p>
    
    <p>Category : {{book_detail.category}}</p>
    <p>Publisher : {{book_detail.publisher}}</p>
    <p>{{book_detail.publish_year}}</p>
    <div class="review">
    <div class="rating">
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star"></i>
    <i class="fas fa-star-half-alt"></i>
    </div>
    <p>(120 Review)</p>
    </div>
    <a class="white-btn mr-10" data-fancybox data-type="iframe" data-src="/viewer.html?file={{ book_detail.pdf.url }}#magazineMode=true" href="javascript:;">Read Now</a>
    {% if book_detail.download == '1' %}
    <a href="{{ book_detail.pdf.url }}" download class="white-btn mr-10">Download</a>
    {% endif %}
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
  
    
    <section class="our-client section-padding best-selling">
    <div class="container">
    <div class="row">
    <div class="offset-xl-1 col-xl-10">
    <div class="nav-button f-left">
    <nav>
    <div class="nav nav-tabs " id="nav-tab" role="tablist">
    <a class="nav-link active" id="nav-one-tab" data-bs-toggle="tab" href="#nav-one" role="tab" aria-controls="nav-one" aria-selected="true">Description</a>
    <a class="nav-link" id="nav-two-tab" data-bs-toggle="tab" href="#nav-two" role="tab" aria-controls="nav-two" aria-selected="false">Author</a>
    </div>
    </nav>
    
    </div>
    </div>
    </div>
    </div>
    <div class="container">
    
    <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-one" role="tabpanel" aria-labelledby="nav-one-tab">
    
    <div class="row">
    <div class="offset-xl-1 col-lg-9">
    <p>
        {{book_detail.description}}
    </p>
    </div>
    </div>
    </div>
    <div class="tab-pane fade" id="nav-two" role="tabpanel" aria-labelledby="nav-two-tab">
    
    <div class="row">
    <div class="offset-xl-1 col-lg-9">
        <p>{{book_detail.author.description}}</p>
    </div>
    </div>
    </div>
    <div class="flip-book-container" src="{{ book_detsil.pdf.url }}"></div>
    </div>
    </div>
    </section>
   
        
      
    </main>
    
{% endblock  %}

books/templates/books.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% block script %}
<script
src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
crossorigin="anonymous"
></script>
 <script>
    $(document).ready(function(){
        $(".filter-checkbox").on('click', function(){
            var filter_object={};
            $(".filter-checkbox").each(function(index,ele){
                var filter_value=$(this).val();
                var filter_key=$(this).data('filter');
                 
                filter_object[filter_key]=Array.from(document.querySelectorAll('input[data-filter='+filter_key+']:checked')).map(function(el){
                     return el.value;
                });
                
            });
            $.ajax({ 
                url:'{% url 'filter_data' %}',
                data:filter_object,
                dataType:'json',		
                success:function(res){				
                    $("#filteredBooks").html(res.data);	
                
                }
            }); 
        });
    });
    </script> 

    {% comment %} <script>

        $(document).ready(function(){
            $(".filter-checkbox").on('click', function(){
                console.log(this)
            });
        });

    </script> {% endcomment %}
 

{% endblock %} 
<main>
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="slider-area">
                    <div class="slider-height2 slider-bg4 d-flex align-items-center justify-content-center">
                        <div class="hero-caption hero-caption2">
                            <h2>Book Category</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="listing-area pt-50 pb-50">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-lg-4 col-md-6">

                    <div class="category-listing mb-50">
                    
                         <div class="single-listing">
                    
                            <div class="select-Categories pb-30">
                                <div class="small-tittle mb-20">
                                    <h4>Filter by Category</h4>
                                </div>
                                {% for i in category %}
                                {% if i.status == '1' %}
                                <div class="single-widget-category">
                                    <label class="container" for="{{i.id}}">{{i.name}}
                                     <input type="checkbox" data-filter="category" id="{{i.id}}" value="{{i.id}}" class="filter-checkbox">
                                     <span class="checkmark"></span><span >({{i.add_book_set.all.count}})</span></label>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    
                    <div class="category-listing mb-50">
                    
                        <div class="single-listing">
                   
                           <div class="select-Categories pb-30">
                               <div class="small-tittle mb-20">
                                   <h4>Filter by Publisher</h4>
                               </div>
                               {% for i in publisher %}
                               {% if i.status == '1' %}
                               <div class="single-widget-category">
                                   <label class="container" for="publisher-{{i.id}}">{{i.name}}
                                    <input type="checkbox" data-filter="publisher" id="publisher-{{i.id}}" value="{{i.id}}" class="filter-checkbox">
                                    <span class="checkmark"></span><span >({{i.add_book_set.all.count}})</span></label>
                               </div>
                               {% endif %}
                               {% endfor %}
                           </div>
                       </div>
                   </div>
                   
                   <div class="category-listing mb-50">
                    
                    <div class="single-listing">
               
                       <div class="select-Categories pb-30">
                           <div class="small-tittle mb-20">
                               <h4>Filter by Publisher</h4>
                           </div>
                           {% for i in author %}
                           {% if i.status == '1' %}
                           <div class="single-widget-category">
                               <label class="container" for="author-{{i.id}}">{{i.name}}
                                <input type="checkbox" data-filter="author" id="author-{{i.id}}" value="{{i.id}}" class="filter-checkbox">
                                <span class="checkmark"></span><span >({{i.add_book_set.all.count}})</span></label>
                           </div>
                           {% endif %}
                           {% endfor %}
                       </div>
                   </div>
               </div>
                </div>
                
                 
                <div class="col-xl-8 col-lg-8 col-md-6">
                    
                    <div class="best-selling p-0">
                        <div class="row" id="filteredBooks">
                            {% for books in books %}
                            {% if books.status == '1' %}
                            <div class="col-xxl-3 col-xl-4 col-lg-4 col-md-12 col-sm-6 book_box">
                                <div class="properties pb-30">
                                    <div class="properties-card">
                                        <div class="properties-img">
                                            <a href="/book_detail/{{books.id}}"><img src="/{{books.image}}" style="height: 298px;" alt=""></a>
                                        </div>
                                        <div class="properties-caption properties-caption2">
                                            <h3><a href="/book_detail/{{books.id}}">{{books.name|truncatewords:2}}</a></h3>
                                            <p>{{books.author}}</p>
                                            <div class="properties-footer d-flex justify-content-between align-items-center">
                                                <div class="review">
                                                    <div class="rating">
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star-half-alt"></i>
                                                    </div>
                                                     <p>(<span>120</span> Review)</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif%}
                            {% endfor %}
                            <div class="row">
                                <div class="col-xl-12">
                                    <div class="more-btn text-center mt-15">
                                            <button id="BrowseMore" class="border-btn border-btn2 more-btn2">Browse More </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</main>
{% endblock %}